### ISSUE TITLE
Links to Terraform files for IAM are incorrect

### ISSUE THREAD

**Issue by r-j-price007** [vallard/K8sClass#11]
The links and locations in the following Readme for the actual terraform templates are incorrect - https://github.com/vallard/K8sClass/blob/master/02/terraform.md  

Specifically, the terraform subdirectory and associated iam and eks directories do not exist in the 02 directory 
cd 02/terraform/iam
cd 02/terraform/eks

**Comment by vallard** [comment]
yeah, you're right.  I updated the class so those have moved and should be fixed in the master branch.  The new class does a bunch of Terragrunt!  
However, I put a link in the main README.md to look at a version back when terraform was in the `02` directory so you should be able to use that.  Sorry it's taken me so long to see this!  I need to set up alerts on this repo!
